CREATE DATABASE IF NOT EXISTS eLight;

USE eLight;

CREATE USER 'user_eLight'@'localhost' IDENTIFIED BY 'lasalle84';
GRANT SELECT, INSERT, UPDATE, DELETE ON eLight.* TO 'user_eLight'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS scenario (
id_scenario INT PRIMARY KEY AUTO_INCREMENT,
nom_scenario VARCHAR(255) NOT NULL,
intensite_scenario INT NOT NULL DEFAULT 200,
date_creation_scenario TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS salle (
id_salle INT PRIMARY KEY AUTO_INCREMENT,
nom_salle VARCHAR(255) UNIQUE NOT NULL,
ip_boitier VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS segment (
id_segment INT PRIMARY KEY AUTO_INCREMENT,
id_salle INT NOT NULL,
id_scenario INT NULL,
ip_segment VARCHAR(15) UNIQUE NOT NULL,
CONSTRAINT fk_segment_salle FOREIGN KEY (id_salle) REFERENCES salle(id_salle) ON DELETE CASCADE,
CONSTRAINT fk_segment_scenario FOREIGN KEY (id_scenario) REFERENCES scenario(id_scenario) ON DELETE SET NULL
);