version: '3'
services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'eLight'
            MYSQL_USER: 'user_eLight'
            MYSQL_PASSWORD: 'lasalle84'
        ports:
            - 3306:3306
        volumes:
            - bdd:/var/lib/mysql
volumes:
    bdd:
