version: '3'
services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'eLight'
        ports:
            - 3306:3306
