CREATE DATABASE IF NOT EXISTS eLight;

USE eLight;

CREATE USER 'user_eLight'@'127.0.0.1' IDENTIFIED BY 'lasalle84';
GRANT SELECT, INSERT, UPDATE, DELETE ON eLight.* TO 'user_eLight'@'127.0.0.1';
FLUSH PRIVILEGES;
